# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LoginApi")

api_instance <- LoginApi$new()

test_that("LoginAccessToken", {
  # tests for LoginAccessToken
  # base path: https://api.chickenstats.com
  # Login Access Token
  # OAuth2 compatible token login, get an access token for future requests.
  # @param username character 
  # @param password character 
  # @param grant_type character  (optional)
  # @param scope character  (optional)
  # @param client_id character  (optional)
  # @param client_secret character  (optional)
  # @return [Token]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RecoverPassword", {
  # tests for RecoverPassword
  # base path: https://api.chickenstats.com
  # Recover Password
  # Password Recovery.
  # @param email character 
  # @return [Message]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RecoverPasswordHtmlContent", {
  # tests for RecoverPasswordHtmlContent
  # base path: https://api.chickenstats.com
  # Recover Password Html Content
  # HTML Content for Password Recovery.
  # @param email character 
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ResetPassword", {
  # tests for ResetPassword
  # base path: https://api.chickenstats.com
  # Reset Password
  # Reset password.
  # @param new_password NewPassword 
  # @return [Message]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TestToken", {
  # tests for TestToken
  # base path: https://api.chickenstats.com
  # Test Token
  # Test access token.
  # @return [UserPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
