# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NewPassword")

model_instance <- NewPassword$new()

test_that("token", {
  # tests for the property `token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`token`, "EXPECTED_RESULT")
})

test_that("new_password", {
  # tests for the property `new_password` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`new_password`, "EXPECTED_RESULT")
})
