# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UsersApi")

api_instance <- UsersApi$new()

test_that("CreateUser", {
  # tests for CreateUser
  # base path: https://api.chickenstats.com
  # Create User
  # Create new user.
  # @param user_create UserCreate 
  # @return [UserPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteUser", {
  # tests for DeleteUser
  # base path: https://api.chickenstats.com
  # Delete User
  # Delete a user.
  # @param user_id character 
  # @return [Message]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteUserMe", {
  # tests for DeleteUserMe
  # base path: https://api.chickenstats.com
  # Delete User Me
  # Delete own user.
  # @return [Message]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadUserById", {
  # tests for ReadUserById
  # base path: https://api.chickenstats.com
  # Read User By Id
  # Get a specific user by id.
  # @param user_id character 
  # @return [UserPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadUserMe", {
  # tests for ReadUserMe
  # base path: https://api.chickenstats.com
  # Read User Me
  # Get current user.
  # @return [UserPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadUsers", {
  # tests for ReadUsers
  # base path: https://api.chickenstats.com
  # Read Users
  # Retrieve users.
  # @param skip integer  (optional)
  # @param limit integer  (optional)
  # @return [UsersPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Signup", {
  # tests for Signup
  # base path: https://api.chickenstats.com
  # Signup
  # Public self-registration. Always creates a free-tier account.
  # @param user_register UserRegister 
  # @return [UserPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdatePasswordMe", {
  # tests for UpdatePasswordMe
  # base path: https://api.chickenstats.com
  # Update Password Me
  # Update own password.
  # @param update_password UpdatePassword 
  # @return [Message]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateUser", {
  # tests for UpdateUser
  # base path: https://api.chickenstats.com
  # Update User
  # Update a user.
  # @param user_id character 
  # @param user_update UserUpdate 
  # @return [UserPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateUserMe", {
  # tests for UpdateUserMe
  # base path: https://api.chickenstats.com
  # Update User Me
  # Update own user.
  # @param user_update_me UserUpdateMe 
  # @return [UserPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
