# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserUpdateMe")

model_instance <- UserUpdateMe$new()

test_that("full_name", {
  # tests for the property `full_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`full_name`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})
