# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Message")

model_instance <- Message$new()

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})
