# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UsersPublic")

model_instance <- UsersPublic$new()

test_that("data", {
  # tests for the property `data` (array[UserPublic])

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("count", {
  # tests for the property `count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`count`, "EXPECTED_RESULT")
})
