# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ValidationError")

model_instance <- ValidationError$new()

test_that("loc", {
  # tests for the property `loc` (array[ValidationErrorLocInner])

  # uncomment below to test the property
  #expect_equal(model.instance$`loc`, "EXPECTED_RESULT")
})

test_that("msg", {
  # tests for the property `msg` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`msg`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("input", {
  # tests for the property `input` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`input`, "EXPECTED_RESULT")
})

test_that("ctx", {
  # tests for the property `ctx` (object)

  # uncomment below to test the property
  #expect_equal(model.instance$`ctx`, "EXPECTED_RESULT")
})
