# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AdminApi")

api_instance <- AdminApi$new()

test_that("CreateLines", {
  # tests for CreateLines
  # base path: https://api.chickenstats.com
  # Create Lines
  # @param lines_create LinesCreate 
  # @return [LinesPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreatePbp", {
  # tests for CreatePbp
  # base path: https://api.chickenstats.com
  # Create Pbp
  # @param pbp_public PbpPublic 
  # @return [PbpPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateStats", {
  # tests for CreateStats
  # base path: https://api.chickenstats.com
  # Create Stats
  # @param stats_create StatsCreate 
  # @return [StatsGame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateTeamStats", {
  # tests for CreateTeamStats
  # base path: https://api.chickenstats.com
  # Create Team Stats
  # @param team_stats_create TeamStatsCreate 
  # @return [TeamStatsPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
