# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RefreshTokenRequest")

model_instance <- RefreshTokenRequest$new()

test_that("refresh_token", {
  # tests for the property `refresh_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`refresh_token`, "EXPECTED_RESULT")
})
